
import Dashboard from "@/app/dashboard/page";
import type {Metadata} from "next";
export const metadata: Metadata = {
  title: "Near Vault",
  description: "Generated by create next app",
}
export default function Home() {
  // return (
  //     <Dashboard/>
  // )
  return <div>home page</div>;
}
